apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: social-media-secret-store
  namespace: social-media
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: social-media
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: social-media-frontend-secrets
  namespace: social-media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: social-media-secret-store
    kind: SecretStore
  target:
    name: social-media-frontend-secrets
    creationPolicy: Owner
  data:
    - secretKey: sentryDsn
      remoteRef:
        key: /social-media/observability
        property: sentryDsn
    - secretKey: apiKey
      remoteRef:
        key: /social-media/frontend
        property: apiKey
