apiVersion: v1
kind: Service
metadata:
  name: social-media-frontend
  namespace: social-media
  labels:
    app.kubernetes.io/name: social-media-frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: social-media-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: social-media-frontend-preview
  namespace: social-media
  labels:
    app.kubernetes.io/name: social-media-frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: social-media-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
